name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-#{{github.ref}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Build
      run: |
        npm install
        gulp

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
